
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class ComplaintSuggesionAdded
{

    public int ID { get; set; }

    public Nullable<int> ComplaintID { get; set; }

    public string ComplaintNo { get; set; }

    public Nullable<System.DateTime> ComplaintSubmitDate { get; set; }

    public string ComplaintSubmitby { get; set; }

    public string ApplicationCauseId { get; set; }

    public string SubstrateCauseID { get; set; }

    public string ProductQualityRetailedID { get; set; }

    public string Remarks { get; set; }

    public Nullable<int> IsVerified { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public string IsVerifiedName { get; set; }

    public string ImageUrl { get; set; }

    public string VideoUrl { get; set; }

    public string ApplicationCaseName { get; set; }

    public string SubstrateCaseName { get; set; }

    public string QualityProductName { get; set; }

}

}
