
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_SaveComplaints
{

    public int ID { get; set; }

    public Nullable<int> SOID { get; set; }

    public Nullable<int> CustomerID { get; set; }

    public Nullable<int> DealerID { get; set; }

    public Nullable<int> ProductID { get; set; }

    public Nullable<int> ProductNatureID { get; set; }

    public string ProductBatchNo { get; set; }

    public string ShakingTime { get; set; }

    public string ColorCode { get; set; }

    public Nullable<decimal> Quantity { get; set; }

    public Nullable<bool> WetSampleAttached { get; set; }

    public string SubstrateColor { get; set; }

    public string TinningRatio { get; set; }

    public string NoOfCoatsApplied { get; set; }

    public string TimeDurationWithinCoats { get; set; }

    public Nullable<int> ThinningSolventID { get; set; }

    public Nullable<int> AppliedToolID { get; set; }

    public string Remarks { get; set; }

    public string Picture1 { get; set; }

    public string Picture2 { get; set; }

    public string VoiceNote { get; set; }

    public string Video { get; set; }

    public string Status { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public string StrickerPicture { get; set; }

}

}
