
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FOS.DataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Tbl_ComplaintUpdate
{

    public int ID { get; set; }

    public Nullable<int> ComplaintID { get; set; }

    public string ComplaintNumber { get; set; }

    public Nullable<System.DateTime> LauncedTime { get; set; }

    public Nullable<int> LaunchedBy { get; set; }

    public Nullable<int> ComplaintStatusID { get; set; }

    public Nullable<int> ProgressStatusID { get; set; }

    public Nullable<System.DateTime> LastUpdatedAt { get; set; }

    public string Picture { get; set; }

    public string Audio { get; set; }

    public string Video { get; set; }

    public string Remarks { get; set; }

}

}
